name: Roseline
url: https://github.com/roseline124/hexo-theme-brewski.git

menu:
  Home: /
  Archives: /archives
  Categories: /categories
  GitHub: https://github.com/roseline124/
  RSS: /atom.xml

favicon: /favicon.svg
logo: /logo.svg

# Disqus shortname
disqus: hyunji_song

# Analytics
google_analytics:

# Copyright Infomation
copyright:
  since: 2019
  name: Roseline_Song
  url: https://roseline-song.netlify.com/
